Simplify the name update call stack
containers/storage pull request #1385
Opened 2022-10-13 20:10 UTC by mtrmac

Instead of going
-	3 store methods
-	store.updateNames+enum
-	3 sub-store methods
-	subStore.updateNames+enum
-	applyNameOperation+enum,

simplify to
-	3 store methods
-	store.updateNames+enum
-	subStore.updateNames+enum
-	applyNameOperation+enum,

Should not change behavior. Looking purely at `updateNameOperation`, invalid values would now be detected after making more work, but there is no way for an external caller to trigger use of an invalid value anyway.

2022-10-13 21:44 UTC, rhatdan commented
LGTM
@nalind @flouthoc @giuseppe @vrothberg @saschagrunert @umohnani8 PTAL

2022-10-14 07:53 UTC, vrothberg reviewed
LGTM, needs a rebase @mtrmac

2022-10-14 08:01 UTC, flouthoc requested changes
`RemoveNames` and `AddNames` are not deprecated instead they were added only to deprecate racy `SetNames`. Here: https://github.com/containers/storage/pull/1153

Downstream is still using `RemoveNames` or `AddNames` and this breaks public API without any deprecation notice IMHO.

Last switch in one of the downstreams happend here https://github.com/containers/buildah/pull/4190 but there are many more PR's.

2022-10-14 14:28 UTC, nalind commented
I'm fine with dropping the methods from rwLayerStore/rwImageStore/rwContainerStore - those are package-private types.  The exported interfaces don't change, so LGTM.

2022-10-14 14:46 UTC, flouthoc commented
> I'm fine with dropping the methods from rwLayerStore/rwImageStore/rwContainerStore - those are package-private types. The exported interfaces don't change, so LGTM.

Ah i see, SGTM as well since I see downstreams only using `Store` directly which is still public so that clears my doubt. LGTM

@mtrmac There is a conflict in the PR though, could you please rebase.

2022-10-14 14:46 UTC, flouthoc approved these changes

2022-10-14 15:56 UTC, mtrmac commented
Rebased, tests pass.

2022-10-14 17:45 UTC, merged