bring read mappings proc into c/storage
containers/storage pull request #1882
Opened 2024-04-09 20:15 UTC by kannon92

As I was working on https://github.com/cri-o/cri-o/pull/7990, I found that ReadMappingsProc was the only function that was missing from pkg/unshare.

@giuseppe mention that this would be a good candidate for c/storage.

This PR adds this function to pkg/unshare. Once this is released, we could drop this from podman.

2024-04-09 20:48 UTC, giuseppe approved these changes
LGTM

2024-04-09 20:49 UTC, giuseppe requested changes
second thoughts: should we just use GetHostIDMappings in Podman?

2024-04-09 20:54 UTC, rhatdan commented
@giuseppe they are trying to stop using Podman code.

2024-04-09 20:54 UTC, rhatdan commented
We could make Podman use this interface possibly?

2024-04-09 20:54 UTC, rhatdan commented
LGTM

2024-04-09 20:55 UTC, merged

2024-04-10 07:53 UTC, giuseppe commented
> @giuseppe they are trying to stop using Podman code.

I understand that, but if we already have an existing function doing the same thing (as it seems to be `GetHostIDMappings`), we can just use that.

@kannon92 can you please try using `GetHostIDMappings` in CRI-O?  If that works for you, we can drop `ReadMappingsProc`

2024-04-10 09:56 UTC, giuseppe commented
I've opened a PR for Podman to drop the function and use the existing function from c/storage: https://github.com/containers/podman/pull/22328

We can do the same in CRI-O and not require `podman/pkg/rootless`

2024-04-10 11:31 UTC, kannon92 commented
I see. I did use that in https://github.com/cri-o/cri-o/pull/7990.

We can drop this PR if you think the above one is the right way to go.

2024-04-10 14:30 UTC, giuseppe commented
> I see. I did use that in [cri-o/cri-o#7990](https://github.com/cri-o/cri-o/pull/7990).
> 
> We can drop this PR if you think the above one is the right way to go.

yes let's just revert this change.  I've opened a PR: https://github.com/containers/storage/pull/1884