chunked: add check for more parts
containers/storage pull request #2160
Opened 2024-11-05 12:00 UTC by giuseppe

validate that there are no other parts returned by the client, and do not ignore other errors that could have happened later.

2024-11-05 14:16 UTC, cgwalters reviewed
It'd be useful to have a bit more context about this - did you find this through code auditing or did it come out of a user hitting it in reality?

2024-11-05 14:16 UTC, cgwalters commented on pkg/chunked/storage_linux.go
>  	_, err = io.CopyBuffer(destination, r, c.copyBuffer)
Aren't we ignoring this error now?

2024-11-05 14:16 UTC, cgwalters commented on pkg/chunked/storage_linux.go
> +		if closed == 2 {
I am confused why we have this counter instead of checking `err` and `err1`

2024-11-05 14:40 UTC, mtrmac requested changes
I think this doesn’t quite work as is, and https://issues.redhat.com/browse/OCPBUGS-43968 suggests that we need either a redesign or a much more careful error handling.

---

Also, unless the code becomes somehow trivial, I think the consumption of `(streams, errs)`, starting with the first `select` already, should be strongly centralized in a helper, not copy&pasted. (We do have some helpers, but those are already copy&pasted instead of used universally.)

2024-11-05 14:40 UTC, mtrmac commented on pkg/chunked/storage_linux.go
> +				closed++
AFAICS once this happens, this `case` will _always_ trigger and this function will consume 100% of a CPU until the other channel is closed.

2024-11-05 14:40 UTC, mtrmac commented on pkg/chunked/storage_linux.go
> +			} else if err == nil {
Nothing guarantees that we read the error from `errs` before we read from this channel. `select` is explicitly designed to choose randomly.

2024-11-05 14:41 UTC, mtrmac commented on pkg/chunked/storage_linux.go
> +				closed++
… and `close` will keep incrementing.

2024-11-05 15:01 UTC, giuseppe commented
I close this PR for now.  I'll redesign to address https://issues.redhat.com/browse/OCPBUGS-43968

2024-11-05 15:01 UTC, closed without merging

2024-11-06 10:12 UTC, giuseppe commented
alternative fix: https://github.com/containers/storage/pull/2162